version: '3'
services:
  web:
    image: php:8.3.11-apache
    container_name: php8311apache
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www/html/
    networks:
      - con
networks:
  con:
